version: "3.3"
services:
  mariadb:
    image: mariadb:10.2
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample-rest-api
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - ./dumps/init.sql:/docker-entrypoint-initdb.d/init.sql
